[package]
name = "nestc"
description = "Bootstrap compiler for the Nest programming language."
authors = ["Oliwier Michalik"]
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "thin"

[dependencies]
logos = "0.16.1"
thiserror = "2.0.20"

[dev-dependencies]
insta = "1.48.0"
