id = "nest"
name = "Nest"
version = "0.1.0"
schema_version = 1
authors = ["Oliwier Michalik"]
description = "Nest: syntax highlighting, and diagnostics from its language server."
repository = "https://github.com/olix3001/Nest"

[grammars.nest]
repository = "https://github.com/olix3001/Nest"
rev = "3d943ffc78760187628610100a8b243bf718773a"
path = "editors/tree-sitter-nest"

[language_servers.nest-lsp]
name = "nest-lsp"
languages = ["Nest"]
