id = "nest"
name = "Nest"
version = "0.1.0"
schema_version = 1
authors = ["Oliwier Michalik"]
description = "Nest: syntax highlighting, and diagnostics from its language server."
repository = "https://github.com/olix3001/Nest"

[grammars.nest]
repository = "https://github.com/olix3001/Nest"
rev = "563ef5295c79b8153a520e1ffe508a9f1bb3b18a"
path = "editors/tree-sitter-nest"

[language_servers.nest-lsp]
name = "nest-lsp"
languages = ["Nest"]
