id = "nest"
name = "Nest"
version = "0.1.0"
schema_version = 1
authors = ["Oliwier Michalik"]
description = "Nest: syntax highlighting, and diagnostics from its language server."
repository = "https://github.com/olix3001/Nest"

[grammars.nest]
repository = "https://github.com/olix3001/Nest"
rev = "d2b0cb867b4a6a06fe20b28a62ac22cbe2a88f30"
path = "editors/tree-sitter-nest"

[language_servers.nest-lsp]
name = "nest-lsp"
languages = ["Nest"]
